# Generated by Django 5.0.6 on 2024-05-10 13:55

import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiasSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='criação')),
                ('modificado_em', models.DateField(auto_now=True, verbose_name='atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('dia', models.CharField(choices=[('seg', 'segunta-feira'), ('ter', 'terça-feira'), ('qua', 'quarta-feira'), ('qui', 'quinta-feira'), ('sex', 'sexta-feira')], max_length=15, verbose_name='Dia')),
                ('horario', models.TimeField(verbose_name='Horarios')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='criação')),
                ('modificado_em', models.DateField(auto_now=True, verbose_name='atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('bio', models.TextField(max_length=200, verbose_name='Bio')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='professor', variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem')),
                ('facebook', models.CharField(default='#', max_length=100, verbose_name='facebook')),
                ('instagram', models.CharField(default='#', max_length=100, verbose_name='instagram')),
                ('linkedin', models.CharField(default='#', max_length=100, verbose_name='linkedIn')),
                ('x', models.CharField(default='#', max_length=100, verbose_name='x')),
                ('disponibilidade', models.ManyToManyField(to='core.diassemana', verbose_name='Disponibilidade')),
            ],
            options={
                'verbose_name': 'Professor',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='criação')),
                ('modificado_em', models.DateField(auto_now=True, verbose_name='atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('carga_horaria', models.IntegerField(max_length=3, verbose_name='Carga horaria')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.professor', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Disciplina',
            },
        ),
    ]
