# Generated by Django 5.0.6 on 2024-05-21 02:05

import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiasSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='criação')),
                ('modificado_em', models.DateField(auto_now=True, verbose_name='atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('dia', models.CharField(choices=[('seg', 'Segunda-feira'), ('ter', 'Terça-feira'), ('qua', 'Quarta-feira'), ('qui', 'Quinta-feira'), ('sex', 'Sexta-feira')], max_length=3, verbose_name='Dia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='criação')),
                ('modificado_em', models.DateField(auto_now=True, verbose_name='atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('periodo', models.CharField(choices=[('1º Período', '1º Período'), ('2º Período', '2º Período'), ('3º Período', '3º Período'), ('4º Período', '4º Período')], max_length=20, verbose_name='Período')),
                ('inicio', models.TimeField(verbose_name='Horário de início')),
                ('fim', models.TimeField(verbose_name='Horário de fim')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='criação')),
                ('modificado_em', models.DateField(auto_now=True, verbose_name='atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('bio', models.TextField(max_length=200, verbose_name='Bio')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='professor', variations={'thumb': {'crop': True, 'height': 200, 'width': 200}}, verbose_name='Imagem')),
                ('facebook', models.CharField(default='#', max_length=100, verbose_name='facebook')),
                ('instagram', models.CharField(default='#', max_length=100, verbose_name='instagram')),
                ('linkedin', models.CharField(default='#', max_length=100, verbose_name='linkedIn')),
                ('x', models.CharField(default='#', max_length=100, verbose_name='x')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='criação')),
                ('modificado_em', models.DateField(auto_now=True, verbose_name='atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('numero', models.IntegerField(default=True, verbose_name='Quantidade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='criação')),
                ('modificado_em', models.DateField(auto_now=True, verbose_name='atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('semana', models.ManyToManyField(to='core.diassemana', verbose_name='Disponibilidade')),
                ('professor', models.ManyToManyField(to='core.professor', verbose_name='Professor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='criação')),
                ('modificado_em', models.DateField(auto_now=True, verbose_name='atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga horaria')),
                ('Professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professor', verbose_name='Professores')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='QTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='criação')),
                ('modificado_em', models.DateField(auto_now=True, verbose_name='atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
                ('disponibilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disponibilidade')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
