# Generated by Django 5.0.6 on 2024-05-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.IntegerField(verbose_name='Carga horaria'),
        ),
    ]
