# Generated by Django 5.0.6 on 2024-05-21 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='Professor',
        ),
        migrations.RemoveField(
            model_name='disponibilidade',
            name='professor',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='Professor',
            field=models.ManyToManyField(related_name='disciplinas', to='core.professor', verbose_name='Professores'),
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='professor',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='core.professor', verbose_name='Professor'),
        ),
    ]
