# Generated by Django 5.0.6 on 2024-05-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_disciplina_carga_horaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='diassemana',
            name='horario_fim',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Horarios'),
        ),
    ]
