# Generated by Django 5.0.6 on 2024-05-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_professor_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diassemana',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='diassemana',
            name='horario_fim',
        ),
        migrations.AddField(
            model_name='diassemana',
            name='horario_1_fim',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='1º Horário de fim'),
        ),
        migrations.AddField(
            model_name='diassemana',
            name='horario_1_inicio',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='1º Horário de início'),
        ),
        migrations.AddField(
            model_name='diassemana',
            name='horario_2_fim',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='2º Horário de fim'),
        ),
        migrations.AddField(
            model_name='diassemana',
            name='horario_2_inicio',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='2º Horário de início'),
        ),
        migrations.AddField(
            model_name='diassemana',
            name='horario_3_fim',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='3º Horário de fim'),
        ),
        migrations.AddField(
            model_name='diassemana',
            name='horario_3_inicio',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='3º Horário de início'),
        ),
        migrations.AddField(
            model_name='diassemana',
            name='horario_4_fim',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='4º Horário de fim'),
        ),
        migrations.AddField(
            model_name='diassemana',
            name='horario_4_inicio',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='4º Horário de início'),
        ),
        migrations.AlterField(
            model_name='diassemana',
            name='dia',
            field=models.CharField(choices=[('seg', 'Segunda-feira'), ('ter', 'Terça-feira'), ('qua', 'Quarta-feira'), ('qui', 'Quinta-feira'), ('sex', 'Sexta-feira')], max_length=3, verbose_name='Dia'),
        ),
    ]
