# Generated by Django 5.0.6 on 2024-05-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_diassemana_horario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='criação')),
                ('modificado_em', models.DateField(auto_now=True, verbose_name='atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('periodo', models.CharField(choices=[('1', '1º Período'), ('2', '2º Período'), ('3', '3º Período'), ('4', '4º Período')], max_length=1, verbose_name='Período')),
                ('inicio', models.TimeField(verbose_name='Horário de início')),
                ('fim', models.TimeField(verbose_name='Horário de fim')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='diassemana',
            name='horario_1_fim',
        ),
        migrations.RemoveField(
            model_name='diassemana',
            name='horario_1_inicio',
        ),
        migrations.RemoveField(
            model_name='diassemana',
            name='horario_2_fim',
        ),
        migrations.RemoveField(
            model_name='diassemana',
            name='horario_2_inicio',
        ),
        migrations.RemoveField(
            model_name='diassemana',
            name='horario_3_fim',
        ),
        migrations.RemoveField(
            model_name='diassemana',
            name='horario_3_inicio',
        ),
        migrations.RemoveField(
            model_name='diassemana',
            name='horario_4_fim',
        ),
        migrations.RemoveField(
            model_name='diassemana',
            name='horario_4_inicio',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='professor',
        ),
    ]
