# Generated by Django 5.0.6 on 2024-05-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_horario_remove_diassemana_horario_1_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='periodo',
            field=models.CharField(choices=[('1º Período', '1º Período'), ('2º Período', '2º Período'), ('3º Período', '3º Período'), ('4º Período', '4º Período')], max_length=20, verbose_name='Período'),
        ),
    ]
