# Generated by Django 5.0.6 on 2024-05-18 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_professor_disponibilidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='disponibilidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diassemana', verbose_name='Disponibilidade'),
        ),
    ]
