# Generated by Django 5.0.6 on 2024-05-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_professor_disponibilidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='disponibilidade',
        ),
        migrations.AddField(
            model_name='professor',
            name='disponibilidade',
            field=models.ManyToManyField(blank=True, to='core.diassemana', verbose_name='Disponibilidade'),
        ),
    ]
