# Generated by Django 5.0.6 on 2024-05-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_professor_disponibilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='disponibilidade',
            field=models.ManyToManyField(to='core.diassemana', verbose_name='Disponibilidade'),
        ),
    ]
