# Generated by Django 5.0.6 on 2024-05-18 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_professor_disponibilidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='disponibilidade',
        ),
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diassemana')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professor')),
            ],
            options={
                'unique_together': {('professor', 'dia_semana')},
            },
        ),
    ]
