# Generated by Django 5.0.6 on 2024-05-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_professor_disponibilidade_disponibilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidade',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='criado_em',
            field=models.DateField(default='2022-01-01', verbose_name='criação'),
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='modificado_em',
            field=models.DateField(auto_now=True, verbose_name='atualização'),
        ),
    ]
