# Generated by Django 5.0.6 on 2024-05-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_disponibilidade_ativo_disponibilidade_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='criado_em',
            field=models.DateField(auto_now_add=True, verbose_name='criação'),
        ),
    ]
