# Generated by Django 5.0.6 on 2024-05-18 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_disponibilidade_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.professor'),
        ),
    ]
