# Generated by Django 5.0.6 on 2024-05-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_professor_disponibilidade_delete_disponibilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='disponibilidade',
            field=models.ManyToManyField(blank=True, related_name='professores', to='core.diassemana', verbose_name='Disponibilidade'),
        ),
    ]
