# Generated by Django 5.0.6 on 2024-05-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_turma_remove_professor_disponibilidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='criação')),
                ('modificado_em', models.DateField(auto_now=True, verbose_name='atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('professor', models.ManyToManyField(to='core.professor', verbose_name='Professores')),
                ('semana', models.ManyToManyField(to='core.diassemana', verbose_name='Disponibilidade')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
