# Generated by Django 5.0.6 on 2024-05-18 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_disponibilidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='QTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='criação')),
                ('modificado_em', models.DateField(auto_now=True, verbose_name='atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
                ('disponibilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disponibilidade')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='disciplina',
            name='professores',
            field=models.ManyToManyField(through='core.QTS', to='core.professor', verbose_name='Professores'),
        ),
    ]
