# Generated by Django 5.0.6 on 2024-05-18 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_disciplina_professores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='professores',
        ),
        migrations.CreateModel(
            name='DisciplinaProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='criação')),
                ('modificado_em', models.DateField(auto_now=True, verbose_name='atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professor')),
            ],
            options={
                'verbose_name': 'Disciplina do Professor',
                'verbose_name_plural': 'Disciplinas dos Professores',
            },
        ),
    ]
